version: "3.3"

services:
  hub-kr:
    container_name: "pytorchkr"
    build: .
    ports:
      - "50001:50001"
    volumes:
      - .:/hub-kr/_preview

    networks:
      - local-net

networks:
  local-net:
    driver: bridge